name: app_imc
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_masked_text: ^0.8.0
  mobx:
  flutter_mobx:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
